export const queries = {
    getAllAZ: 'EXECUTE getAZ',
    getAllBoleta_ENLA:'EXECUTE getBoleta_ENLA',
    getAllBoleta_PRC:'EXECUTE getBoleta_PRC',
    getAllCAS:'EXECUTE getCAS',
    getAllCIM:'EXECUTE getCIM',
    getAllConcepto_ENLA: 'EXECUTE getConcepto_ENLA',
    getAllConceptos_PRC: 'EXECUTE getConceptos_PRC',
    getAllENT: 'EXECUTE getENT',
    getAllFormato: 'EXECUTE getFormato',
    getAllHID: 'EXECUTE getHID',
    getAllReporte_Terminado: 'EXECUTE getReporte_Terminado',
    getAllRevisiones_ENLA: 'EXECUTE getRevisiones_ENLA',
    getAllRevisionFinal_ENLA: 'EXECUTE getRevisionFinal_ENLA',
    getAllSAN: 'EXECUTE getSAN',
    getAllTrazo: 'EXECUTE getTrazo',
    getAllValores_ENLA: 'EXECUTE getValores_ENLA',
    getAllValores_PRC: 'EXECUTE getValores_PRC',
    getAllValorRevision_ENLA: 'EXECUTE getValorRevision_ENLA',
    getAllContratista: 'SELECT * FROM EKCloud.dbo.emo_contratistas',
    getAllSupervisor: 'SELECT * FROM EKCloud.dbo.emo_supervisor',
    getAllDesarrollo: 'SELECT * FROM EKCloud.dbo.emo_desarrollos',
    getAllPrototipo: 'SELECT * FROM EKCloud.dbo.emo_prototipos',

    postNewAZ: 'EXECUTE postAZ @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@RevisarIsometrico,@RevisarDespiece,@RevisarDiametroTuberia,@UbicacionSalidasElec,@CortesCajas,@GuiadoPoliductoElec,@ConcretoBombeado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@CimbraBuenasCondiciones,@MadrinasPerimetro,@ContraflechaLosa,@NivelacionCimbra,@TaponearEnraseBlock,@UbicacionSalidasHidra,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@ModulacionViguetaBovedilla,@TipoMalla,@TrabeLosa,@VarillasTrabes,@EstribosTrabes,@RefuerzoMalla,@RefuerzoEnCastillos,@RefuerzoDeCastillos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillosPretil,@Vibrado,@EspesorComprension,@AcabadoAvionLosaCompacta,@Curado,@Geolocalizacion',
    postNewBoleta_ENLA:'EXECUTE postBoleta_ENLA @IdFormato,@Id_Coordinador,@Id_Contratista,@Id_Supervisor,@Id_Residente',
    postNewBoleta_PRC:'EXECUTE postBoleta_ENLA @IdFormato,@Id_Contratista,@Id_RepresentanteProduccion,@Id_RepresentantePostVenta',
    postNewCAS:'EXECUTE postCAS @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@Madera,@Desmoldante,@Apoyo,@NivelacionCimbra,@Plomo,@DesplantePb,@JunteoBlockPb,@Escalerilla3raPb,@Escalerilla6taPb,@Escalerilla9naPb,@Escalerilla11vaPb,@ConcretoPremezclado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@BajadasPluviales,@RamaleosHidraulicos,@RamaleosElectricos,@PreparacionAireAcondicionado,@Trazo,@NivelacionEscalera,@Cimbra,@Armado,@Concreto,@Colado,@TipoCastillo,@TipoCerramiento,@Varillas,@Estribos,@Refuerzos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@Vibrado,@Recubrimiento,@Curado,@DesplantePa,@JunteoBlockPa,@Escalerilla3raPa,@Escalerilla6taPa,@Escalerilla9naPa,@Escalerilla11vaPa,@DesplantePre,@JunteoBlockPre,@Escalerilla3raPre,@Escalerilla6taPre,@Escalerilla9naPre,@Escalerilla11vaPre',
    postNewCIM:'EXECUTE postCIM @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@SeccionMin,@PendienteMinExcavacion,@PendienteMinInstalacion,@AlimentacionElectrica,@ForjadoRegistros,@MedidasCanas,@TapasProvisionales,@ProfundidadNivel,@ConcretoTirado,@fcConcreto,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@Revenimiento,@Alineacion,@NivelacionCimbra,@Sujecion,@ColocacionHule,@Desmoldante,@UbicacionSalidas,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@PruebaHidraulica,@TipoMallaZapata,@TipoMallaFirme,@TrabeCimentacionZapata,@TrabeCimentacionFirme,@VarillasTrabeZapata,@VarillasTrabeFirme,@EstriboTrabeZapata,@EstriboTrabeFirme,@RefuerzoMallaZapata,@RefuerzoMallaFirme,@ArmexCastilloZapata,@ArmexCastilloFirme,@RefuerzoCastilloZapata,@RefuerzoCastilloFirme,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillo,@ContraventeoBAP,@Vibrado,@Espesor,@NivelacionColado,@Acabado,@Curado',
    postNewConcepto_ENLA: 'EXECUTE postConcepto_ENLA @Concepto',
    postNewConceptos_PRC: 'EXECUTE postConceptos_PRC @Conceptos',
    postNewENT: 'EXECUTE postENT @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@RevisarIsometricoElec,@RevisarDespieceElec,@RevisarDiametroElec,@UbicacionSalidasElec,@CortesCajas,@GuiadoPoliducto,@RevisarIsometricoSani,@RevisarDespieceSani,@RevisarDiametroSani,@UbicacionSalidasSani,@PendienteMinTubo,@PruebaFluidez,@Gas,@ConcretoBombeado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@CimbraBuenasCondiciones,@MadrinasPerimetro,@ContraflechaLosa,@NivelacionCimbra,@TaponearEnrase,@UbicacionSalidas,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@Encamisado,@PruebaHidraulica,@ModulacionVigueta,@TipoMalla,@TrabeLosa,@VarillasTrabes,@EstribosTrabes,@RefuerzoMalla,@RefuerzoEnCastillos,@RefuerzoDeCastillos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillosPretil,@ContraventeoBAP,@Vibrado,@EspesorComprension,@AcabadoAvionLosaCompacta,@Curado,@Geolocalizacion',
    postNewFormato: 'EXECUTE postFormato @Id_Fraccionamiento,@Id_Etapa,@Fecha',
    postNewHID: 'EXECUTE postHID @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@PresionInicialPlantaBaja,@HoraInicialPlantaBaja,@PresionFinalPlantaBaja,@HoraFinalPlantaBaja,@FechaPlantaBaja,@ObservacionesPlantaBaja,@FechaRevisionPlantaBaja,@DescripcionAcuerdoPlantaBaja,@FechaCumplimientoPlantaBaja,@PresionInicialPlantaAlta,@HoraInicialPlantaAlta,@PresionFinalPlantaAlta,@HoraFinalPlantaAlta,@FechaPlantaAlta,@ObservacionesPlantaAlta,@FechaRevisionPlantaAlta,@DescripcionAcuerdoPlantaAlta,@FechaCumplimientoPlantaAlta,@Geolocalizacion',
    postNewReporte_Terminado: 'EXECUTE postReporte_Terminado @IdFormato,@Observaciones',
    postNewRevisiones_ENLA: 'EXECUTE postRevisiones_ENLA @Revision',
    postNewRevisionFinal_ENLA: 'EXECUTE postRevisionFinal_ENLA @IdRevision,@Fecha,@Observacion',
    postNewSAN: 'EXECUTE postSAN @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@Forjado,@MediasCañas,@TiposDiametro,@PendienteTuboCimentacion,@NumeroCimentacion,@FechaRevisionCimentacion,@FechaCumplimientoCimentacion,@ConcentracionCimentacion,@NivelSardinel,@TipoDiametro,@PendienteTuboEntrepiso,@NumeroEntrepiso,@FechaRevisionEntrepiso,@FechaCumplimientoEntrepiso,@ConcentracionEntrepiso,@Geolocalizacion',
    postNewTrazo: 'EXECUTE postTrazo @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@PuntosManzaneros,@Lotificacion,@PuntosRadio,@Escuadras,@PuntosControl,@NivelesPlataforma,@NivelGuarnicion,@TomasDomicilarias,@DescargasSanitarias,@AcometidasElectricas,@GasNatural',
    postNewValores_ENLA: 'EXECUTE postValores_ENLA @IdBoleta,@IdRevision,@IdValorRevision,@IdConcepto,@Geolocalizacion',
    postNewValores_PRC: 'EXECUTE postValores_PRC @Id_Boleta, @Id_Concepto,@Cumple,@Observaciones,FechaValidacion',
    postNewValorRevision_ENLA:'EXECUTE postValorRevision_ENLA @Valor',
    getAZById: 'EXECUTE getAZById @Id',
    getBoleta_ENLAById: 'EXECUTE getBoleta_ENLAById @Id',
    getBoleta_PRCById: 'EXECUTE getBoleta_PRCById @Id',
    getCASById: 'EXECUTE getCASById @Id',
    getCIMById: 'EXECUTE getCIMById @Id',
    getConcepto_ENLAById: 'EXECUTE getConcepto_ENLAById @Id',
    getConceptos_PRCById: 'EXECUTE getConceptos_PRCById @Id',
    getENTById: 'EXECUTE getENTById @Id',
    getFormatoById: 'EXECUTE getFormatoById @Id',
    getHIDById: 'EXECUTE getHIDById @Id',
    getReporte_TerminadoById: 'EXECUTE getReporte_TerminadoById @Id',
    getRevisiones_ENLAById: 'EXECUTE getRevisiones_ENLAById @Id',
    getRevisionFinal_ENLAById: 'EXECUTE getRevisionFinal_ENLAById @Id',
    getSANById: 'EXECUTE getSANById @Id',
    getTrazoById: 'EXECUTE getTrazoById @Id',
    getValores_ENLAById: 'EXECUTE getValores_ENLAById @Id',
    getValores_PRCById: 'EXECUTE getValores_PRCById @Id',
    getValorRevision_ENLAById: 'EXECUTE getValorRevision_ENLAById @Id',
    deleteAZ:'EXECUTE deleteAZ @Id',
    deleteBoleta_PRC: 'EXECUTE deleteBoleta_PRC @Id',
    deleteBoleta_ENLA: 'EXECUTE deleteBoleta_ENLA @Id',
    deleteCAS: 'EXECUTE deleteCAS @Id',
    deleteCIM:'EXECUTE deleteCIM @Id',
    deleteConceptos_PRC: 'EXECUTE deleteConceptos_PRC @Id',
    deleteConcepto_ENLA: 'EXECUTE deleteConcepto_ENLA @Id',
    deleteENT: 'EXECUTE deleteENT @Id',
    deleteFormato: 'EXECUTE deleteFormato @Id',
    deleteHID: 'EXECUTE deleteHID @Id',
    deleteReporte_Terminado: 'EXECUTE deleteReporte_Terminado @Id',
    deleteRevisiones_ENLA: 'EXECUTE deleteRevisiones_ENLA @Id',
    deleteRevisionFinal_ENLA: 'EXECUTE deleteRevisionFinal_ENLA @Id',
    deleteSAN: 'EXECUTE deleteSAN @Id',
    deleteTrazo: 'EXECUTE deleteTrazo @Id',
    deleteValores_ENLA: 'EXECUTE deleteValores_ENLA @Id',
    deleteValores_PRC: 'EXECUTE deleteValores_PRC @Id',
    deleteValorRevision_ENLA: 'EXECUTE deleteValorRevision_ENLA @Id',
    updateAZ: 'EXECUTE updateAZ @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@RevisarIsometrico,@RevisarDespiece,@RevisarDiametroTuberia,@UbicacionSalidasElec,@CortesCajas,@GuiadoPoliductoElec,@ConcretoBombeado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@CimbraBuenasCondiciones,@MadrinasPerimetro,@ContraflechaLosa,@NivelacionCimbra,@TaponearEnraseBlock,@UbicacionSalidasHidra,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@ModulacionViguetaBovedilla,@TipoMalla,@TrabeLosa,@VarillasTrabes,@EstribosTrabes,@RefuerzoMalla,@RefuerzoEnCastillos,@RefuerzoDeCastillos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillosPretil,@Vibrado,@EspesorComprension,@AcabadoAvionLosaCompacta,@Curado,@Geolocalizacion',
    updateBoleta_PRC: 'EXECUTE updateBoleta_PRC @IdFormato,@Id_Contratista,@Id_RepresentanteProduccion,@Id_RepresentantePostVenta',
    updateBoleta_ENLA: 'EXECUTE updateBoleta_ENLA @IdFormato,@Id_Coordinador,@Id_Contratista,@Id_Supervisor,@Id_Residente',
    updateCAS: 'EXECUTE updateCAS @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@Madera,@Desmoldante,@Apoyo,@NivelacionCimbra,@Plomo,@Desplante,@JunteoBlock,@Escalerilla3ra,@Escalerilla6ta,@Escalerilla9na,@Escalerilla11va,@ConcretoPremezclado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@BajadasPluviales,@RamaleosHidraulicos,@RamaleosElectricos,@PreparacionAireAcondicionado,@Trazo,@NivelacionEscalera,@Cimbra,@Armado,@Concreto,@Colado,@TipoCastillo,@TipoCerramiento,@Varillas,@Estribos,@Refuerzos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@Vibrado,@Recubrimiento,@Curado,@DesplantePa,@JunteoBlockPa,@Escalerilla3raPa,@Escalerilla6taPa,@Escalerilla9naPa,@Escalerilla11vaPa,@DesplantePre,@JunteoBlockPre,@Escalerilla3raPre,@Escalerilla6taPre,@Escalerilla9naPre,@Escalerilla11vaPre,@Geolocalizacion',
    updateCIM: 'EXECUTE updateCIM @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@SeccionMin,@PendienteMinExcavacion,@PendienteMinInstalacion,@AlimentacionElectrica,@ForjadoRegistros,@MedidasCañas,@TapasProvisionales,@ProfundidadNivel,@ConcretoTirado,@fcConcreto,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@Revenimiento,@Alineacion,@NivelacionCimbra,@Sujecion,@ColocacionHule,@Desmoldante,@UbicacionSalidas,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@PruebaHidraulica,@TipoMallaZapata,@TipoMallaFirme,@TrabeCimentacionZapata,@TrabeCimentacionFirme,@VarillasTrabeZapata,@VarillasTrabeFirme,@EstriboTrabeZapata,@EstriboTrabeFirme,@RefuerzoMallaZapata,@RefuerzoMallaFirme,@ArmexCastilloZapata,@ArmexCastilloFirme,@RefuerzoCastilloZapata,@RefuerzoCastilloFirme,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillo,@ContraventeoBAP,@Vibrado,@Espesor,@NivelacionColado,@Acabado,@Curado,@Geolocalizacion',
    updateConceptos_PRC: 'EXECUTE updateConceptos_PRC @Conceptos',
    updateConcepto_ENLA: 'EXECUTE updateConcepto_ENLA @Concepto',
    updateENT: 'EXECUTE updateENT @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@RevisarIsometricoElec,@RevisarDespieceElec,@RevisarDiametroElec,@UbicacionSalidasElec,@CortesCajas,@GuiadoPoliducto,@RevisarIsometricoSani,@RevisarDespieceSani,@RevisarDiametroSani,@UbicacionSalidasSani,@PendienteMinTubo,@PruebaFluidez,@Gas,@ConcretoBombeado,@fcConcreto,@Revenimiento,@Cilindro7dias,@Cilindro14dias,@Cilindro28dias,@CimbraBuenasCondiciones,@MadrinasPerimetro,@ContraflechaLosa,@NivelacionCimbra,@TaponearEnrase,@UbicacionSalidas,@RevisionConexiones,@DiametrosTuberia,@TipoTuberia,@Encamisado,@PruebaHidraulica,@ModulacionVigueta,@TipoMalla,@TrabeLosa,@VarillasTrabes,@EstribosTrabes,@RefuerzoMalla,@RefuerzoEnCastillos,@RefuerzoDeCastillos,@Traslapes,@Dobleces,@Amarres,@Anclajes,@Calzado,@Bayoneteo,@UbicacionCastillosPretil,@ContraventeoBAP,@Vibrado,@EspesorComprension,@AcabadoAvionLosaCompacta,@Curado,@Geolocalizacion',
    updateFormato: 'EXECUTE updateFormato @Id_Etapa,@Fecha',
    updateHID: 'EXECUTE updateHID @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@PresionInicialPlantaBaja,@HoraInicialPlantaBaja,@PresionFinalPlantaBaja,@HoraFinalPlantaBaja,@FechaPlantaBaja,@ObservacionesPlantaBaja,@FechaRevisionPlantaBaja,@DescripcionAcuerdoPlantaBaja,@FechaCumplimientoPlantaBaja,@PresionInicialPlantaAlta,@HoraInicialPlantaAlta,@PresionFinalPlantaAlta,@HoraFinalPlantaAlta,@FechaPlantaAlta,@ObservacionesPlantaAlta,@FechaRevisionPlantaAlta,@DescripcionAcuerdoPlantaAlta,@FechaCumplimientoPlantaAlta,@Geolocalizacion',
    updateReporte_Terminado:'EXECUTE updateReporte_Terminado @IdFormato,@Observaciones',
    updateRevisiones_ENLA:'EXECUTE updateRevisiones_ENLA @Revision',
    updateRevisionFinal_ENLA:'EXECUTE updateRevisionFinal_ENLA @IdRevision,@Fecha,@Observacion',
    updateSAN:'EXECUTE updateSAN @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@Forjado,@MediasCañas,@TiposDiametro,@PendienteTuboCimentacion,@NumeroCimentacion,@FechaRevisionCimentacion,@FechaCumplimientoCimentacion,@ConcentracionCimentacion,@NivelSardinel,@TipoDiametro,@PendienteTuboEntrepiso,@NumeroEntrepiso,@FechaRevisionEntrepiso,@FechaCumplimientoEntrepiso,@ConcentracionEntrepiso,@Geolocalizacion',
    updateTrazo: 'EXECUTE updateTrazo @IdFormato,@IdContratista,@IdSupervisor,@IdResidente,@PuntosManzaneros,@Lotificacion,@PuntosRadio,@Escuadras,@PuntosControl,@NivelesPlataforma,@NivelGuarnicion,@TomasDomicilarias,@DescargasSanitarias,@AcometidasElectricas,@GasNatural',
    updateValores_PRC: 'EXECUTE updateValores_PRC @Id_Boleta, @Id_Concepto,@Cumple,@Observaciones,@FechaValidacion',
    updateValores_ENLA: 'EXECUTE updateValores_ENLA @IdBoleta,@IdRevision,@IdValorRevision,@IdConcepto,@Geolocalizacion',
    updateValorRevision_ENLA: 'EXECUTE updateValorRevision_ENLA @Valor'
}